<a href="https://colab.research.google.com/github/SarahAdmin/April-Housing-Notebook/blob/main/April_Housing_Notebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
averageDF = pd.read_csv('Average-prices-2025-04.csv',encoding='latin-1')
final_average = averageDF.head(200)
final_average.style.background_gradient(cmap='gist_rainbow')

/usr/local/lib/python3.11/dist-packages/pandas/io/formats/style.py:3807: RuntimeWarning: All-NaN slice encountered
  smin = np.nanmin(gmap) if vmin is None else vmin
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/style.py:3808: RuntimeWarning: All-NaN slice encountered
  smax = np.nanmax(gmap) if vmax is None else vmax

In [ ]:
salesDF = pd.read_csv('Sales-2025-04.csv',encoding='latin-1')
final_sales = salesDF.head(200)
final_sales.style.background_gradient(cmap='gist_rainbow')

In [ ]:
cashDF = pd.read_csv('Cash-mortgage-sales-2025-04.csv',encoding='latin-1')
newCash = cashDF.head(500)
newCash.style.background_gradient(cmap='gist_rainbow')

/usr/local/lib/python3.11/dist-packages/pandas/io/formats/style.py:3807: RuntimeWarning: All-NaN slice encountered
  smin = np.nanmin(gmap) if vmin is None else vmin
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/style.py:3808: RuntimeWarning: All-NaN slice encountered
  smax = np.nanmax(gmap) if vmax is None else vmax